on:
  workflow_dispatch:
    inputs:
      commit_sha:
        description: "commit to deploy to prod"
        required: true
        type: string

name: PromoteToProd
run-name: Promote To Prod

jobs:
  deploy_prod:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Dummy(Todo) Promote to Prod for commit ${{ inputs.commit_sha }}"
